### ISSUE TITLE
Where's the server of localhost:8000?

### ISSUE THREAD

**Issue by eldyvoon** [vkbansal/learn-flux#2]
I run `gulp` it does not give me a server. How to run this demo?

**Comment by vkbansal** [comment]
My bad. I've not updated this repo since long!.

you need to run `npm start` to start the server.

**Comment by eldyvoon** [comment]
@vkbansal Still got error. Error getting `GET http://192.168.56.1:8080/react-alt/app.js `

and I can't run npm run build, webpack failed. Please see http://i.imgur.com/syF6VYV.png

**Comment by vkbansal** [comment]
I'll try to debug this tonight and report back.

**Comment by vkbansal** [comment]
I've update the scripts and README. Please let me know if you still face issues.
